#开发环境配置

server:
  #https
  port: 7000
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useAffectedRows=true
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: true  #启用表单REST风格
    contentnegotiation:
      favor-parameter: true  #开启请求参数内容协商

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl